class DataList:
    search_data = [
        {
            "case_name": "样本编号精准搜索",
            "search_items": {"sampleNo": ["25S06160003"]}
        },
        {
            "case_name": "样本编号模糊搜索",
            "search_items": {"sampleNo": ["111"]}
        },
        {
            "case_name": "样本编号批量搜索",
            "search_items": {"sampleNo": ["25S06160002", "25S06160003"]}
        },
        {
            "case_name": "芯片ID模糊搜索",
            "search_items": {"chipCode": "V3502"}
        },
        {
            "case_name": "任务编号模糊搜索",
            "search_items": {"seqTaskCode": "R2509"}
        },
        {
            "case_name": "任务状态批量搜索",
            "search_items": {"status": ["START", "WAITING"]}
        },
        {
            "case_name": "创建日期搜索",
            "search_items": {"createTime": "2025-06-01,2025-07-31"}
        },
        {
            "case_name": "组合搜索",
            "search_items": {"sampleNo": ["11"], "chipCode": "V35", "seqTaskCode": "R2508", "status": ["START"],
                             "createTime": "2025-06-01,2025-10-30"}
        }
    ]

    sequence_data = [
        {
            "case_name": "创建单芯片任务(无法流转至分析中心)",
            "option": "clear",
            "task_items": [
                {
                    "chipCode": "Test123456",
                    "extractionKit": "提取试剂批号1",
                    "libraryKit": "建库试剂批号1",
                    "libraryOperator": "建库操作人1",
                    "sequenceKit": "测序试剂批号1",
                    "sequenceOperator": "测序操作人1",
                    "sequencePlatform": "MGISEQ-2000",
                    "sequencerId": "MGISEQ-2000",
                    "lanes": [
                        {
                            "lane": "L01",
                            "dnbId": "DNB111",
                            "poolingId": "Pooling111",
                            "tableData": [
                                {
                                    "barcode": 1,
                                    "collectDate": "2025-07-01 00:00:00",
                                    "dnaConcentration": 1,
                                    "dnbConcentration": 9,
                                    "flowId": "3628335",
                                    "hospitalName": "罗湖中医院",
                                    "libraryConcentration": 5,
                                    "patientName": "测试1",
                                    "poolingId": "Pooling111",
                                    "productName": "",
                                    "productNo": "DX0006",
                                    "projectCode": "CNV-seq",
                                    "sampleId": "532946341828104192",
                                    "sampleNo": "25B09188817",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "S370",
                                    "sampleIndex": 1,
                                    "umi": 1,
                                    "lane": "L01",
                                    "dnbId": "DNB111",
                                    "notHavePoolingIds": [
                                        "Pooling111"
                                    ],
                                    "sampleProductId": "532946341828104193",
                                    "panelType": "",
                                    "__index__": 9,
                                    "selectable": "false",
                                    "projectType": "0",
                                    "fontId": "eVzVBYfEaQ"
                                },
                                {
                                    "barcode": 2,
                                    "collectDate": "2025-09-17 00:00:00",
                                    "dnaConcentration": 2,
                                    "dnbConcentration": 10,
                                    "flowId": "3628343",
                                    "hospitalName": "罗湖中医院",
                                    "libraryConcentration": 6,
                                    "patientName": "NIFTY添加",
                                    "poolingId": "Pooling111",
                                    "productName": "",
                                    "productNo": "DX0558",
                                    "projectCode": "NIFTY",
                                    "sampleId": "532946342390140928",
                                    "sampleNo": "25B09188848",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "S051",
                                    "sampleIndex": 2,
                                    "umi": 2,
                                    "lane": "L01",
                                    "dnbId": "DNB111",
                                    "notHavePoolingIds": [
                                        "Pooling111"
                                    ],
                                    "sampleProductId": "532946342394335232",
                                    "panelType": "",
                                    "__index__": 10,
                                    "selectable": "false",
                                    "projectType": "1",
                                    "fontId": "JLmuPE0goi"
                                },
                                {
                                    "barcode": 3,
                                    "collectDate": "2025-09-17 00:00:00",
                                    "dnaConcentration": 3,
                                    "dnbConcentration": 11,
                                    "flowId": "3628351",
                                    "hospitalName": "测试添加",
                                    "libraryConcentration": 7,
                                    "patientName": "携带者添加",
                                    "poolingId": "Pooling111",
                                    "productName": "",
                                    "productNo": "DX1605",
                                    "projectCode": "CS",
                                    "sampleId": "532946342931206144",
                                    "sampleNo": "25B09188879",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "L001",
                                    "sampleIndex": 3,
                                    "umi": 3,
                                    "lane": "L01",
                                    "dnbId": "DNB111",
                                    "notHavePoolingIds": [
                                        "Pooling111"
                                    ],
                                    "sampleProductId": "532946342935400448",
                                    "panelType": "Y155",
                                    "__index__": 11,
                                    "selectable": "false",
                                    "projectType": "2",
                                    "fontId": "ztjrGsieHk"
                                },
                                {
                                    "barcode": 4,
                                    "collectDate": "2025-09-17 00:00:00",
                                    "dnaConcentration": 4,
                                    "dnbConcentration": 12,
                                    "flowId": "3628359",
                                    "hospitalName": "测试添加",
                                    "libraryConcentration": 8,
                                    "patientName": "新生儿添加",
                                    "poolingId": "Pooling111",
                                    "productName": "",
                                    "productNo": "DX1968",
                                    "projectCode": "NBS",
                                    "sampleId": "532946343392579584",
                                    "sampleNo": "25B09188911",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "L001",
                                    "sampleIndex": 4,
                                    "umi": 4,
                                    "lane": "L01",
                                    "dnbId": "DNB111",
                                    "notHavePoolingIds": [
                                        "Pooling111"
                                    ],
                                    "sampleProductId": "532946343396773888",
                                    "panelType": "NBS",
                                    "__index__": 12,
                                    "selectable": "false",
                                    "projectType": "0",
                                    "fontId": "mEfRcxixHK"
                                }
                            ],
                            "notHavePoolingIds": [
                                "Pooling111"
                            ]
                        },
                        {
                            "lane": "L02",
                            "dnbId": "DNB222",
                            "poolingId": "",
                            "tableData": [
                                {
                                    "barcode": 1,
                                    "collectDate": "2025-09-17 00:00:00",
                                    "dnaConcentration": "",
                                    "dnbConcentration": "",
                                    "flowId": "3622490",
                                    "hospitalName": "测试添加",
                                    "libraryConcentration": "",
                                    "patientName": "携带者添加",
                                    "poolingId": "",
                                    "productName": "",
                                    "productNo": "DX1605",
                                    "projectCode": "CS",
                                    "sampleId": "532619262351773696",
                                    "sampleNo": "25B09177628",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "L001",
                                    "sampleIndex": "",
                                    "umi": "",
                                    "lane": "L02",
                                    "dnbId": "DNB222",
                                    "sampleProductId": "532619262355968000",
                                    "panelType": "Y155",
                                    "__index__": 26,
                                    "selectable": "false",
                                    "projectType": "0",
                                    "fontId": "4FB3iCshkl"
                                },
                                {
                                    "barcode": 2,
                                    "collectDate": "2025-09-17 00:00:00",
                                    "dnaConcentration": "",
                                    "dnbConcentration": "",
                                    "flowId": "3622612",
                                    "hospitalName": "测试添加",
                                    "libraryConcentration": "",
                                    "patientName": "新生儿添加",
                                    "poolingId": "",
                                    "productName": "",
                                    "productNo": "DX1968",
                                    "projectCode": "NBS",
                                    "sampleId": "532620241541402624",
                                    "sampleNo": "1123X",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "L001",
                                    "sampleIndex": "",
                                    "umi": "",
                                    "lane": "L02",
                                    "dnbId": "DNB222",
                                    "sampleProductId": "532620241541402625",
                                    "panelType": "NBS",
                                    "__index__": 25,
                                    "selectable": "false",
                                    "projectType": "1",
                                    "fontId": "3M5YfTToJ4"
                                },
                                {
                                    "barcode": 3,
                                    "collectDate": "2025-09-17 00:00:00",
                                    "dnaConcentration": "",
                                    "dnbConcentration": "",
                                    "flowId": "3622482",
                                    "hospitalName": "罗湖中医院",
                                    "libraryConcentration": "",
                                    "patientName": "NIFTY添加",
                                    "poolingId": "",
                                    "productName": "",
                                    "productNo": "DX0558",
                                    "projectCode": "NIFTY",
                                    "sampleId": "532616737141690368",
                                    "sampleNo": "25B09175573",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "S051",
                                    "sampleIndex": "",
                                    "umi": "",
                                    "lane": "L02",
                                    "dnbId": "DNB222",
                                    "sampleProductId": "532616737141690369",
                                    "panelType": "",
                                    "__index__": 27,
                                    "selectable": "false",
                                    "projectType": "2",
                                    "fontId": "r38yxcCyFD"
                                },
                                {
                                    "barcode": 4,
                                    "collectDate": "2025-07-01 00:00:00",
                                    "dnaConcentration": "",
                                    "dnbConcentration": "",
                                    "flowId": "3621811",
                                    "hospitalName": "罗湖中医院",
                                    "libraryConcentration": "",
                                    "patientName": "测试1",
                                    "poolingId": "",
                                    "productName": "",
                                    "productNo": "DX0006",
                                    "projectCode": "CNV-seq",
                                    "sampleId": "532584049009627136",
                                    "sampleNo": "25B09172123",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "S370",
                                    "sampleIndex": "",
                                    "umi": "",
                                    "lane": "L02",
                                    "dnbId": "DNB222",
                                    "sampleProductId": "532584049009627137",
                                    "panelType": "",
                                    "__index__": 39,
                                    "selectable": "false",
                                    "projectType": "0",
                                    "fontId": "yNklkIR2f2"
                                }
                            ]
                        }
                    ],
                    "samples": [
                        {
                            "barcode": 1,
                            "collectDate": "2025-07-01 00:00:00",
                            "dnaConcentration": 1,
                            "dnbConcentration": 9,
                            "flowId": "3628335",
                            "hospitalName": "罗湖中医院",
                            "libraryConcentration": 5,
                            "patientName": "测试1",
                            "poolingId": "Pooling111",
                            "productName": "",
                            "productNo": "DX0006",
                            "projectCode": "CNV-seq",
                            "sampleId": "532946341828104192",
                            "sampleNo": "25B09188817",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "S370",
                            "sampleIndex": 1,
                            "umi": 1,
                            "lane": "L01",
                            "dnbId": "DNB111",
                            "notHavePoolingIds": [
                                "Pooling111"
                            ],
                            "sampleProductId": "532946341828104193",
                            "panelType": "",
                            "__index__": 9,
                            "selectable": "false",
                            "projectType": "0",
                            "fontId": "eVzVBYfEaQ"
                        },
                        {
                            "barcode": 2,
                            "collectDate": "2025-09-17 00:00:00",
                            "dnaConcentration": 2,
                            "dnbConcentration": 10,
                            "flowId": "3628343",
                            "hospitalName": "罗湖中医院",
                            "libraryConcentration": 6,
                            "patientName": "NIFTY添加",
                            "poolingId": "Pooling111",
                            "productName": "",
                            "productNo": "DX0558",
                            "projectCode": "NIFTY",
                            "sampleId": "532946342390140928",
                            "sampleNo": "25B09188848",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "S051",
                            "sampleIndex": 2,
                            "umi": 2,
                            "lane": "L01",
                            "dnbId": "DNB111",
                            "notHavePoolingIds": [
                                "Pooling111"
                            ],
                            "sampleProductId": "532946342394335232",
                            "panelType": "",
                            "__index__": 10,
                            "selectable": "false",
                            "projectType": "1",
                            "fontId": "JLmuPE0goi"
                        },
                        {
                            "barcode": 3,
                            "collectDate": "2025-09-17 00:00:00",
                            "dnaConcentration": 3,
                            "dnbConcentration": 11,
                            "flowId": "3628351",
                            "hospitalName": "测试添加",
                            "libraryConcentration": 7,
                            "patientName": "携带者添加",
                            "poolingId": "Pooling111",
                            "productName": "",
                            "productNo": "DX1605",
                            "projectCode": "CS",
                            "sampleId": "532946342931206144",
                            "sampleNo": "25B09188879",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "L001",
                            "sampleIndex": 3,
                            "umi": 3,
                            "lane": "L01",
                            "dnbId": "DNB111",
                            "notHavePoolingIds": [
                                "Pooling111"
                            ],
                            "sampleProductId": "532946342935400448",
                            "panelType": "Y155",
                            "__index__": 11,
                            "selectable": "false",
                            "projectType": "2",
                            "fontId": "ztjrGsieHk"
                        },
                        {
                            "barcode": 4,
                            "collectDate": "2025-09-17 00:00:00",
                            "dnaConcentration": 4,
                            "dnbConcentration": 12,
                            "flowId": "3628359",
                            "hospitalName": "测试添加",
                            "libraryConcentration": 8,
                            "patientName": "新生儿添加",
                            "poolingId": "Pooling111",
                            "productName": "",
                            "productNo": "DX1968",
                            "projectCode": "NBS",
                            "sampleId": "532946343392579584",
                            "sampleNo": "25B09188911",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "L001",
                            "sampleIndex": 4,
                            "umi": 4,
                            "lane": "L01",
                            "dnbId": "DNB111",
                            "notHavePoolingIds": [
                                "Pooling111"
                            ],
                            "sampleProductId": "532946343396773888",
                            "panelType": "NBS",
                            "__index__": 12,
                            "selectable": "false",
                            "projectType": "0",
                            "fontId": "mEfRcxixHK"
                        },
                        {
                            "barcode": 1,
                            "collectDate": "2025-09-17 00:00:00",
                            "dnaConcentration": "",
                            "dnbConcentration": "",
                            "flowId": "3622490",
                            "hospitalName": "测试添加",
                            "libraryConcentration": "",
                            "patientName": "携带者添加",
                            "poolingId": "",
                            "productName": "",
                            "productNo": "DX1605",
                            "projectCode": "CS",
                            "sampleId": "532619262351773696",
                            "sampleNo": "25B09177628",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "L001",
                            "sampleIndex": "",
                            "umi": "",
                            "lane": "L02",
                            "dnbId": "DNB222",
                            "sampleProductId": "532619262355968000",
                            "panelType": "Y155",
                            "__index__": 26,
                            "selectable": "false",
                            "projectType": "0",
                            "fontId": "4FB3iCshkl"
                        },
                        {
                            "barcode": 2,
                            "collectDate": "2025-09-17 00:00:00",
                            "dnaConcentration": "",
                            "dnbConcentration": "",
                            "flowId": "3622612",
                            "hospitalName": "测试添加",
                            "libraryConcentration": "",
                            "patientName": "新生儿添加",
                            "poolingId": "",
                            "productName": "",
                            "productNo": "DX1968",
                            "projectCode": "NBS",
                            "sampleId": "532620241541402624",
                            "sampleNo": "1123X",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "L001",
                            "sampleIndex": "",
                            "umi": "",
                            "lane": "L02",
                            "dnbId": "DNB222",
                            "sampleProductId": "532620241541402625",
                            "panelType": "NBS",
                            "__index__": 25,
                            "selectable": "false",
                            "projectType": "1",
                            "fontId": "3M5YfTToJ4"
                        },
                        {
                            "barcode": 3,
                            "collectDate": "2025-09-17 00:00:00",
                            "dnaConcentration": "",
                            "dnbConcentration": "",
                            "flowId": "3622482",
                            "hospitalName": "罗湖中医院",
                            "libraryConcentration": "",
                            "patientName": "NIFTY添加",
                            "poolingId": "",
                            "productName": "",
                            "productNo": "DX0558",
                            "projectCode": "NIFTY",
                            "sampleId": "532616737141690368",
                            "sampleNo": "25B09175573",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "S051",
                            "sampleIndex": "",
                            "umi": "",
                            "lane": "L02",
                            "dnbId": "DNB222",
                            "sampleProductId": "532616737141690369",
                            "panelType": "",
                            "__index__": 27,
                            "selectable": "false",
                            "projectType": "2",
                            "fontId": "r38yxcCyFD"
                        },
                        {
                            "barcode": 4,
                            "collectDate": "2025-07-01 00:00:00",
                            "dnaConcentration": "",
                            "dnbConcentration": "",
                            "flowId": "3621811",
                            "hospitalName": "罗湖中医院",
                            "libraryConcentration": "",
                            "patientName": "测试1",
                            "poolingId": "",
                            "productName": "",
                            "productNo": "DX0006",
                            "projectCode": "CNV-seq",
                            "sampleId": "532584049009627136",
                            "sampleNo": "25B09172123",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "S370",
                            "sampleIndex": "",
                            "umi": "",
                            "lane": "L02",
                            "dnbId": "DNB222",
                            "sampleProductId": "532584049009627137",
                            "panelType": "",
                            "__index__": 39,
                            "selectable": "false",
                            "projectType": "0",
                            "fontId": "yNklkIR2f2"
                        }
                    ],
                    "isShowSequence": "true"
                }
            ]
        },
        {
            "case_name": "创建多芯片任务(无法流转至分析中心)",
            "option": "clear",
            "task_items": [
                {
                    "chipCode": "V352404121",
                    "extractionKit": "",
                    "libraryKit": "建库试剂批号2",
                    "libraryOperator": "建库操作人1",
                    "sequenceKit": "测序试剂批号3",
                    "sequenceOperator": "",
                    "sequencePlatform": "MGISEQ-2000",
                    "sequencerId": "MGISEQ-2000",
                    "lanes": [
                        {
                            "lane": "L01",
                            "dnbId": "1",
                            "poolingId": "",
                            "tableData": [
                                {
                                    "barcode": 1,
                                    "collectDate": "2025-07-10 00:00:00",
                                    "dnaConcentration": "",
                                    "dnbConcentration": "",
                                    "flowId": "3649795",
                                    "hospitalName": "深圳北大医院",
                                    "libraryConcentration": "",
                                    "patientName": "AutoTest012418",
                                    "poolingId": "",
                                    "productName": "",
                                    "productNo": "DX0007",
                                    "projectCode": "CNV-seq",
                                    "sampleId": "534306561158418432",
                                    "sampleNo": "Auto0012418",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "S370",
                                    "sampleIndex": "",
                                    "umi": "",
                                    "lane": "L01",
                                    "dnbId": "1",
                                    "sampleProductId": "534306561158418433",
                                    "panelType": "",
                                    "__index__": 8,
                                    "selectable": "false",
                                    "projectType": "0",
                                    "fontId": "8TSuemHHlB"
                                },
                                {
                                    "barcode": 2,
                                    "collectDate": "2025-07-01 00:00:00",
                                    "dnaConcentration": "",
                                    "dnbConcentration": "",
                                    "flowId": "3628335",
                                    "hospitalName": "罗湖中医院",
                                    "libraryConcentration": "",
                                    "patientName": "测试1",
                                    "poolingId": "",
                                    "productName": "",
                                    "productNo": "DX0006",
                                    "projectCode": "CNV-seq",
                                    "sampleId": "532946341828104192",
                                    "sampleNo": "25B09188817",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "S370",
                                    "sampleIndex": "",
                                    "umi": "",
                                    "lane": "L01",
                                    "dnbId": "1",
                                    "sampleProductId": "532946341828104193",
                                    "panelType": "",
                                    "__index__": 9,
                                    "selectable": "false",
                                    "projectType": "2",
                                    "fontId": "vA9EvtRNRP"
                                }
                            ]
                        }
                    ],
                    "samples": [
                        {
                            "barcode": 1,
                            "collectDate": "2025-07-10 00:00:00",
                            "dnaConcentration": "",
                            "dnbConcentration": "",
                            "flowId": "3649795",
                            "hospitalName": "深圳北大医院",
                            "libraryConcentration": "",
                            "patientName": "AutoTest012418",
                            "poolingId": "",
                            "productName": "",
                            "productNo": "DX0007",
                            "projectCode": "CNV-seq",
                            "sampleId": "534306561158418432",
                            "sampleNo": "Auto0012418",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "S370",
                            "sampleIndex": "",
                            "umi": "",
                            "lane": "L01",
                            "dnbId": "1",
                            "sampleProductId": "534306561158418433",
                            "panelType": "",
                            "__index__": 8,
                            "selectable": "false",
                            "projectType": "0",
                            "fontId": "8TSuemHHlB"
                        },
                        {
                            "barcode": 2,
                            "collectDate": "2025-07-01 00:00:00",
                            "dnaConcentration": "",
                            "dnbConcentration": "",
                            "flowId": "3628335",
                            "hospitalName": "罗湖中医院",
                            "libraryConcentration": "",
                            "patientName": "测试1",
                            "poolingId": "",
                            "productName": "",
                            "productNo": "DX0006",
                            "projectCode": "CNV-seq",
                            "sampleId": "532946341828104192",
                            "sampleNo": "25B09188817",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "S370",
                            "sampleIndex": "",
                            "umi": "",
                            "lane": "L01",
                            "dnbId": "1",
                            "sampleProductId": "532946341828104193",
                            "panelType": "",
                            "__index__": 9,
                            "selectable": "false",
                            "projectType": "2",
                            "fontId": "vA9EvtRNRP"
                        }
                    ],
                    "isShowSequence": "true"
                },
                {
                    "chipCode": "S200044901",
                    "extractionKit": "提取试剂批号4",
                    "libraryKit": "",
                    "libraryOperator": "",
                    "sequenceKit": "",
                    "sequenceOperator": "测序操作人5",
                    "sequencePlatform": "MGISEQ-200",
                    "sequencerId": "200-241209",
                    "lanes": [
                        {
                            "lane": "L01",
                            "dnbId": "11",
                            "poolingId": "",
                            "tableData": [
                                {
                                    "barcode": 1,
                                    "collectDate": "2025-09-17 00:00:00",
                                    "dnaConcentration": "",
                                    "dnbConcentration": "",
                                    "flowId": "3628351",
                                    "hospitalName": "测试添加",
                                    "libraryConcentration": "",
                                    "patientName": "携带者添加",
                                    "poolingId": "",
                                    "productName": "",
                                    "productNo": "DX1605",
                                    "projectCode": "CS",
                                    "sampleId": "532946342931206144",
                                    "sampleNo": "25B09188879",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "L001",
                                    "sampleIndex": "",
                                    "umi": "",
                                    "lane": "L01",
                                    "dnbId": "11",
                                    "sampleProductId": "532946342935400448",
                                    "panelType": "Y155",
                                    "__index__": 11,
                                    "selectable": "false",
                                    "projectType": "0",
                                    "fontId": "LYs1lmctbh"
                                },
                                {
                                    "barcode": 2,
                                    "collectDate": "2025-09-17 00:00:00",
                                    "dnaConcentration": "",
                                    "dnbConcentration": "",
                                    "flowId": "3628359",
                                    "hospitalName": "测试添加",
                                    "libraryConcentration": "",
                                    "patientName": "新生儿添加",
                                    "poolingId": "",
                                    "productName": "",
                                    "productNo": "DX1968",
                                    "projectCode": "NBS",
                                    "sampleId": "532946343392579584",
                                    "sampleNo": "25B09188911",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "L001",
                                    "sampleIndex": "",
                                    "umi": "",
                                    "lane": "L01",
                                    "dnbId": "11",
                                    "sampleProductId": "532946343396773888",
                                    "panelType": "NBS",
                                    "__index__": 12,
                                    "selectable": "false",
                                    "projectType": "1",
                                    "fontId": "D0juNuvZEV"
                                }
                            ]
                        }
                    ],
                    "samples": [
                        {
                            "barcode": 1,
                            "collectDate": "2025-09-17 00:00:00",
                            "dnaConcentration": "",
                            "dnbConcentration": "",
                            "flowId": "3628351",
                            "hospitalName": "测试添加",
                            "libraryConcentration": "",
                            "patientName": "携带者添加",
                            "poolingId": "",
                            "productName": "",
                            "productNo": "DX1605",
                            "projectCode": "CS",
                            "sampleId": "532946342931206144",
                            "sampleNo": "25B09188879",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "L001",
                            "sampleIndex": "",
                            "umi": "",
                            "lane": "L01",
                            "dnbId": "11",
                            "sampleProductId": "532946342935400448",
                            "panelType": "Y155",
                            "__index__": 11,
                            "selectable": "false",
                            "projectType": "0",
                            "fontId": "LYs1lmctbh"
                        },
                        {
                            "barcode": 2,
                            "collectDate": "2025-09-17 00:00:00",
                            "dnaConcentration": "",
                            "dnbConcentration": "",
                            "flowId": "3628359",
                            "hospitalName": "测试添加",
                            "libraryConcentration": "",
                            "patientName": "新生儿添加",
                            "poolingId": "",
                            "productName": "",
                            "productNo": "DX1968",
                            "projectCode": "NBS",
                            "sampleId": "532946343392579584",
                            "sampleNo": "25B09188911",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "L001",
                            "sampleIndex": "",
                            "umi": "",
                            "lane": "L01",
                            "dnbId": "11",
                            "sampleProductId": "532946343396773888",
                            "panelType": "NBS",
                            "__index__": 12,
                            "selectable": "false",
                            "projectType": "1",
                            "fontId": "D0juNuvZEV"
                        }
                    ],
                    "isShowSequence": "true"
                }
            ]
        }
    ]

    delete_data = [
        {
            "case_name": "创建单芯片任务(无法流转至分析中心)",
            "option": "",
            "task_items": [
                {
                    "chipCode": "Test1111",
                    "extractionKit": "提取试剂批号1",
                    "libraryKit": "建库试剂批号1",
                    "libraryOperator": "建库操作人1",
                    "sequenceKit": "测序试剂批号1",
                    "sequenceOperator": "测序操作人1",
                    "sequencePlatform": "MGISEQ-2000",
                    "sequencerId": "MGISEQ-2000",
                    "lanes": [
                        {
                            "lane": "L01",
                            "dnbId": "DNB111",
                            "poolingId": "Pooling111",
                            "tableData": [
                                {
                                    "barcode": 1,
                                    "collectDate": "2025-07-01 00:00:00",
                                    "dnaConcentration": 1,
                                    "dnbConcentration": 9,
                                    "flowId": "3628335",
                                    "hospitalName": "罗湖中医院",
                                    "libraryConcentration": 5,
                                    "patientName": "测试1",
                                    "poolingId": "Pooling111",
                                    "productName": "",
                                    "productNo": "DX0006",
                                    "projectCode": "CNV-seq",
                                    "sampleId": "532946341828104192",
                                    "sampleNo": "25B09188817",
                                    "sampleSetting": "Clinical",
                                    "sampleTypeCode": "S370",
                                    "sampleIndex": 1,
                                    "umi": 1,
                                    "lane": "L01",
                                    "dnbId": "DNB111",
                                    "notHavePoolingIds": [
                                        "Pooling111"
                                    ],
                                    "sampleProductId": "532946341828104193",
                                    "panelType": "",
                                    "__index__": 9,
                                    "selectable": "false",
                                    "projectType": "0",
                                    "fontId": "eVzVBYfEaQ"
                                }
                            ],
                            "notHavePoolingIds": [
                                "Pooling111"
                            ]
                        }
                    ],
                    "samples": [
                        {
                            "barcode": 1,
                            "collectDate": "2025-07-01 00:00:00",
                            "dnaConcentration": 1,
                            "dnbConcentration": 9,
                            "flowId": "3628335",
                            "hospitalName": "罗湖中医院",
                            "libraryConcentration": 5,
                            "patientName": "测试1",
                            "poolingId": "Pooling111",
                            "productName": "",
                            "productNo": "DX0006",
                            "projectCode": "CNV-seq",
                            "sampleId": "532946341828104192",
                            "sampleNo": "25B09188817",
                            "sampleSetting": "Clinical",
                            "sampleTypeCode": "S370",
                            "sampleIndex": 1,
                            "umi": 1,
                            "lane": "L01",
                            "dnbId": "DNB111",
                            "notHavePoolingIds": [
                                "Pooling111"
                            ],
                            "sampleProductId": "532946341828104193",
                            "panelType": "",
                            "__index__": 9,
                            "selectable": "false",
                            "projectType": "0",
                            "fontId": "eVzVBYfEaQ"
                        }
                    ],
                    "isShowSequence": "true"
                }
            ]
        }
    ]

    field_config = [
        {
            "page": "SequencingList",
            "field_base_data": {'createTime': '创建时间', 'chipCode': '芯片ID', 'seqTaskCode': '任务编号', 'sequencerId': '测序仪ID',
                                'sequencePlatform': '测序平台', 'sequenceProgress': '测序进度', 'sequenceStatus': '测序状态',
                                'uploadStatus': '测序数据上传状态', 'seqTaskStatus': '任务状态', 'causeError': '失败原因',
                                'exampleTotal': '样例数量'},
            "field_project_data": {'createTime': '创建时间', 'creator': '创建人', 'chipCode': '芯片ID',
                                   'sequenceStartTime': '测序开始时间', 'sequenceEndTime': '测序结束时间', 'seqTaskCode': '任务编号',
                                   'sequencerId': '测序仪ID', 'sequencePlatform': '测序平台', 'sequenceProgress': '测序进度',
                                   'sequenceStatus': '测序状态', 'uploadStatus': '测序数据上传状态', 'seqTaskStatus': '任务状态',
                                   'causeError': '失败原因', 'exampleTotal': '样例数量'}
        }, {
            "page": "Sequencing",
            "field_base_data": {'productNo': '产品套餐', 'sampleTypeCode': '样本类型', 'barcode': 'Barcode ID', 'poolingId': 'Pooling ID',
                                'sampleSetting': '样本设定', 'instanceNo': '样例编号', 'panelType': '技术路线', 'lane': 'Lane ID',
                                'dnbId': 'DNB ID', 'dnaConcentration': '提取产物浓度', 'libraryConcentration': '建库产物浓度',
                                'dnbConcentration': 'DNB浓度'},
            "field_project_data": {'productNo': '产品套餐', 'sampleTypeCode': '样本类型', 'barcode': 'Barcode ID',
                                   'sampleIndex': 'Index ID', 'umi': 'UMI', 'poolingId': 'Pooling ID', 'sampleSetting': '样本设定',
                                   'projectType': '项目类型', 'instanceNo': '样例编号', 'panelType': '技术路线', 'lane': 'Lane ID',
                                   'dnbId': 'DNB ID', 'dnaConcentration': '提取产物浓度', 'libraryConcentration': '建库产物浓度',
                                   'dnbConcentration': 'DNB浓度'}
        }
    ]
