# 质控品目模板信息
zkp_template_yax_13 = {
        # "num": 49,
        "id": "e-2",
        "type": "controller",
        # "zcatalo": "ZKP0009982YAX-101",
        "controller": "",
        "indexA": "13",
        "indexB": "",
        "noDrop": False,
        "sta": "",
        "zguid": -50,
        "matnr": "RC0091",
        "ztestnum": "",
        "zsample": None,
        "isEmptyNode": False,
        # "ztx": "NIFTY1-48",
        "fragm": "",
        "zmatn4": "",
        "matn4": None,
        "maktx": "NIFTY500平台阴阳质控",
        "zurgent": "",
        "zbq": None,
        "customerName": "",
        "kunnr_name": "",
        "zsjdid": "",
        "stpch": "",
        # "z_fzh": "0002",
        "group_zcatalo": "9999999996",
        "group_zindex": "",
        "group_matn4": "",
        "numsSample": 0,
        "z_jk_qyl": 0,
        "z_jk_qytj": 0,
        "z_jk_te": 0,
        "z_jk_ybsyl": 0,
        "z_jk_ml": 0,
        "z_jk_cycle": 0,
        "z_jk_note": "",
        "matn4_desc": None,
        "zqpcr_chroma": None,
        # "zseqplatform": "MGISEQ-2000",
        "zconcentration": None,
        "zzkpfz_txt": "阳性质控",
        "zprimername": "常规",
        "zconcentration_sj": None,
        "zlrnd": None,
        "zzkpfz": "42",
        "zsfhg": None,
        "merar": None,
        "zzkpbm": "9999999996",
        "zcrwz": "E02",
        "zindex_xl": None,
        "ztech_route": "MAE-MBE-MAX-MBL-MBT-MDE",
        "mat41": None,
        "zprocodenumy": None,
        "zplate_x": 12,
        "zsys_exist": None,
        "zplate_y": 8,
        "zremark": None,
        "zfragmentsize": None,
        "zzkpbm_txt": "阳性质控1",
        "label": "阳性质控1",
        "value": "9999999996",
        # "pre_zcwbh": "ZKP0009982YAX-101",
        "zkpwbbh": "",
        # "zzkpbm_inner": "04$ZKP0009982YAX-101",
        # "ddl21": "SE35+10",
        "zindextype": "indexA",
        "draged": False,
        # "radat": "6M",
        "x": 12,
        "y": 8,
        # "zplate": "P22000084005-01",
        # "count": 2,
        # "zkpCount": 4,
        "zgxbh": "MAE",
        # "_id": 1,
        "pernr": "00000135",
        # "zsyyn": "刘秋芳",
        "zcxlx": "0",
        "zcxlx_des": "手工产线",
        # "zmethod": "1755.01.22",
        # "zmethod_des": "1755.01.22深圳_产前组_提取&建库_产前自动化提取建库",
        # "zshould_finish_datum": "20220922",
        "znote": "",
        "zpoint": "e-2",
        # "zcwbh": "ZKL0009982YAX-101",
        "zindex": "13",
        "zindex_name": "13",
        # "zshould_finish_uzeit": "195621"
    }
zkp_template_yix_13 = {
        # "num": 55,
        "id": "e-8",
        "type": "controller",
        # "zcatalo": "ZKP0009981YIX-101",
        "controller": "",
        "indexA": "13",
        "indexB": "",
        "noDrop": False,
        "sta": "",
        "zguid": -56,
        "matnr": "RC0091",
        "ztestnum": "",
        "zsample": None,
        "isEmptyNode": False,
        # "ztx": "NIFTY1-48",
        "fragm": "",
        "zmatn4": "",
        "matn4": None,
        "maktx": "NIFTY500平台阴阳质控",
        "zurgent": "",
        "zbq": None,
        "customerName": "",
        "kunnr_name": "",
        "zsjdid": "",
        "stpch": "",
        # "z_fzh": "0001",
        "group_zcatalo": "9999999997",
        "group_zindex": "",
        "group_matn4": "",
        "numsSample": 0,
        "z_jk_qyl": 0,
        "z_jk_qytj": 0,
        "z_jk_te": 0,
        "z_jk_ybsyl": 0,
        "z_jk_ml": 0,
        "z_jk_cycle": 0,
        "z_jk_note": "",
        "matn4_desc": None,
        "zqpcr_chroma": None,
        # "zseqplatform": "MGISEQ-2000",
        "zconcentration": None,
        "zzkpfz_txt": "阴性质控",
        "zprimername": "常规",
        "zconcentration_sj": None,
        "zlrnd": None,
        "zzkpfz": "43",
        "zsfhg": None,
        "merar": None,
        "zzkpbm": "9999999997",
        "zcrwz": "E08",
        "zindex_xl": None,
        "ztech_route": "MAE-MBE-MAX-MBL-MBT-MDE",
        "mat41": None,
        "zprocodenumy": None,
        "zplate_x": 12,
        "zsys_exist": None,
        "zplate_y": 8,
        "zremark": None,
        "zfragmentsize": None,
        "zzkpbm_txt": "阴性质控1",
        "label": "阴性质控1",
        "value": "9999999997",
        # "pre_zcwbh": "ZKP0009981YIX-101",
        "zkpwbbh": "",
        # "zzkpbm_inner": "03$ZKP0009981YIX-101",
        # "ddl21": "SE35+10",
        "zindextype": "indexA",
        "draged": False,
        # "radat": "6M",
        "x": 12,
        "y": 8,
        # "zplate": "P22000084005-01",
        # "count": 2,
        # "zkpCount": 4,
        "zgxbh": "MAE",
        # "_id": 1,
        "pernr": "00000135",
        # "zsyyn": "刘秋芳",
        "zcxlx": "0",
        "zcxlx_des": "手工产线",
        # "zmethod": "1755.01.22",
        # "zmethod_des": "1755.01.22深圳_产前组_提取&建库_产前自动化提取建库",
        # "zshould_finish_datum": "20220922",
        "znote": "",
        "zpoint": "e-8",
        # "zcwbh": "ZKL0009981YIX-101",
        "zindex": "13",
        "zindex_name": "13",
        # "zshould_finish_uzeit": "195621"
    }
zkp_template_yix_61 = {
        # "num": 55,
        "id": "e-8",
        "type": "controller",
        # "zcatalo": "ZKP0009981YIX-101",
        "controller": "",
        "indexA": "61",
        "indexB": "",
        "noDrop": False,
        "sta": "",
        "zguid": -56,
        "matnr": "RC0091",
        "ztestnum": "",
        "zsample": None,
        "isEmptyNode": False,
        # "ztx": "NIFTY1-48",
        "fragm": "",
        "zmatn4": "",
        "matn4": None,
        "maktx": "NIFTY500平台阴阳质控",
        "zurgent": "",
        "zbq": None,
        "customerName": "",
        "kunnr_name": "",
        "zsjdid": "",
        "stpch": "",
        # "z_fzh": "0001",
        "group_zcatalo": "9999999997",
        "group_zindex": "",
        "group_matn4": "",
        "numsSample": 0,
        "z_jk_qyl": 0,
        "z_jk_qytj": 0,
        "z_jk_te": 0,
        "z_jk_ybsyl": 0,
        "z_jk_ml": 0,
        "z_jk_cycle": 0,
        "z_jk_note": "",
        "matn4_desc": None,
        "zqpcr_chroma": None,
        # "zseqplatform": "MGISEQ-2000",
        "zconcentration": None,
        "zzkpfz_txt": "阴性质控",
        "zprimername": "常规",
        "zconcentration_sj": None,
        "zlrnd": None,
        "zzkpfz": "43",
        "zsfhg": None,
        "merar": None,
        "zzkpbm": "9999999997",
        "zcrwz": "E08",
        "zindex_xl": None,
        "ztech_route": "MAE-MBE-MAX-MBL-MBT-MDE",
        "mat41": None,
        "zprocodenumy": None,
        "zplate_x": 12,
        "zsys_exist": None,
        "zplate_y": 8,
        "zremark": None,
        "zfragmentsize": None,
        "zzkpbm_txt": "阴性质控1",
        "label": "阴性质控1",
        "value": "9999999997",
        # "pre_zcwbh": "ZKP0009981YIX-101",
        "zkpwbbh": "",
        # "zzkpbm_inner": "03$ZKP0009981YIX-101",
        # "ddl21": "SE35+10",
        "zindextype": "indexA",
        "draged": False,
        # "radat": "6M",
        "x": 12,
        "y": 8,
        # "zplate": "P22000084005-01",
        # "count": 2,
        # "zkpCount": 4,
        "zgxbh": "MAE",
        # "_id": 1,
        "pernr": "00000135",
        # "zsyyn": "刘秋芳",
        "zcxlx": "0",
        "zcxlx_des": "手工产线",
        # "zmethod": "1755.01.22",
        # "zmethod_des": "1755.01.22深圳_产前组_提取&建库_产前自动化提取建库",
        # "zshould_finish_datum": "20220922",
        "znote": "",
        "zpoint": "e-8",
        # "zcwbh": "ZKL0009981YIX-101",
        "zindex": "61",
        "zindex_name": "61",
        # "zshould_finish_uzeit": "195621"
    }
zkp_info_yax = {
        "zcatalo": "9999999996",
        # "zcwbh":"ZKP0009982YAX-10101",
        # "zplate_bcode": "01",
        "id": "e-2"
    }
zkp_info_yix = {
        "zcatalo": "9999999997",
        # "zcwbh":"ZKP0009981YIX-10101",
        # "zplate_bcode": "01",
        "id": "e-8"
    }
